<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Marisa.Backend.OneBot</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Marisa.BotDriver\Marisa.BotDriver.csproj"/>
    </ItemGroup>

    <PropertyGroup>
        <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=.\Marisa.Backend.OneBot\</PathMap>
    </PropertyGroup>

</Project>
